all:  clean compile run

compile: muhammed_ali_gurcan_PA7.c 
	@echo "-------------------------------------------"
	@echo "Compiling..."
	@gcc -o test muhammed_ali_gurcan_PA7.c -lm

run:
	@echo "-------------------------------------------"
	@echo "Running the tests...."
	@echo "=========================="
	@./test
	@echo "\n=========================="
	@echo "Completed tests...."

clean:
	@echo "-------------------------------------------"
	@echo "Cleaning..."
	@rm -f *.o
	@rm -f test
clear:
	@clear	